### ISSUE TITLE
processId is not set during initialize request

### ISSUE THREAD

**Issue by Ekopalypse** [jgmdev/lite-xl-lsp#20]
My understanding is that this must be set when the editor starts the language server

	The process Id of the parent process that started the server. Is null if
	the process has not been started by another process. If the parent
	process is not alive then the server should exit (see exit notification)
	its process.

**Comment by jgmdev** [comment]
I think I left this null because at the moment I didn't know how to retrieve lite-xl process id and I still don't know. Would need to investigate if the lua api exposes this (don't remember) or implement it manually...
