### ISSUE TITLE
Error on merge

### ISSUE THREAD

**Issue by ekkl** [jgmdev/lite-xl-lsp#22]
Hi.
I added lite-xl-lsp, but on start get an error
```
[Thu Feb  3 22:15:21 2022] .../vmf/prog/lite-xl/share/lite-xl/plugins/autocomplete.lua:13: attempt to call field 'merge' (a nil value) at /home/ekkl/vmf/prog/lite-xl/share/lite-xl/core/init.lua:1364
stack traceback:
.../vmf/prog/lite-xl/share/lite-xl/plugins/autocomplete.lua:13: in main chunk
[C]: in function 'require'
/home/ekkl/.config/lite-xl/plugins/lsp/init.lua:27: in main chunk
[C]: in function 'require'
/home/ekkl/.config/lite-xl/plugins/lsp/config.lua:12: in main chunk
[C]: in function 'require'
/home/ekkl/.config/lite-xl/init.lua:54: in main chunk
[C]: in function 'dofile'
/home/ekkl/vmf/prog/lite-xl/share/lite-xl/core/init.lua:818: in function </home/ekkl/vmf/prog/lite-xl/share/lite-xl/core/init.lua:808>
[C]: in function 'xpcall'
/home/ekkl/vmf/prog/lite-xl/share/lite-xl/core/init.lua:1363: in function </home/ekkl/vmf/prog/lite-xl/share/lite-xl/core/init.lua:1361>
(...tail calls...)
/home/ekkl/vmf/prog/lite-xl/share/lite-xl/core/init.lua:970: in function 'init'
[string "local core..."]:8: in function <[string "local core..."]:2>
[C]: in function 'xpcall'
[string "local core..."]:2: in main chunk
```
My init.lua ($HOME/.config/lite-xl/init.lua)
```
local lspconfig = require "plugins.lsp.config"   <----- Line 12

-- lspconfig.clangd.setup {}

lspconfig.sumneko_lua.setup {
    command = {
      "/home/ekkl/vmf/prog/LSP/bin/lua-language-server",
      "-E",
      "/home/ekkl/vmf/prog/LSP/bin/main.lua"
    },
   settings = {
    Lua = {
      diagnostics = {
        enable = false
      }
    }
  }
}
```
autocomplete.lua was changed from original to lsp autocjmplete

**Comment by jgmdev** [comment]
Which version of lite-xl are you using?

I merged a new function to autocomplete.lua that merges a table with another one. It seems to be only available on the master branch of lite-xl so using an older lite-xl version may cause issues. For the moment you can revert the autocomplete.lua to an earlier version like this one: https://github.com/jgmdev/lite-xl-lsp/blob/23552157692df45947cb7de30536325d27965887/autocomplete.lua

**Comment by ekkl** [comment]
My lite-xl  is 2.0.5 vtrsion
If I replaced autoconplete.lua on https://github.com/jgmdev/lite-xl-lsp/blob/23552157692df45947cb7de30536325d27965887/autocomplete.lua the error is gone
But the autocomplete not work for native Lua functions (math etc.)
I also noticed that the lua-language-server itself is not working (i.e. the program is not running)

**Comment by jgmdev** [comment]
Latest lua language server from master is working here, did you followed up this build instructions:
https://github.com/sumneko/lua-language-server/wiki/Build-and-Run

Also it seems this argument isn't needed anymore:
```
"-E",
"/home/ekkl/vmf/prog/LSP/bin/main.lua"
```

Also just to be sure try lite-xl built from master maybe v2.0.5 has some issues.

**Comment by ekkl** [comment]
Thanks, everything worked. Later I can write everything as it was, if you're interested

**Comment by jgmdev** [comment]
> Later I can write everything as it was, if you're interested

Sure, feel free to create the first wiki page entry :)
