### ISSUE TITLE
Create a development branch

### ISSUE THREAD

**Issue by dheisom** [jgmdev/lite-xl-lsp#23]
Hello, you are using functions that only lite-xl development version have and I am trying to run your LSP client on the latest released version(2.0.5), always I try to compile lite-xl manually, this makes too many bugs, and I don't think that all lite-xl users that want to have a LSP want to compile the master version to use a plugin, then please, create a development branch and put the code working on the latest released version of lite-xl in the master branch

**Comment by dheisom** [comment]
The file `lsp/diagnostics.lua` has an error on line 98, you are trying to perform a bitwise operation on a nil value

```text

**Comment by jgmdev** [comment]
I think the only function I depended on master was common.merge on the autocomplete plugin mod that is now part of master. Modified it to work with tagged lite-xl release. Let me know if something else doesn't works

**Comment by dheisom** [comment]
Ok, now this works on latest release, thanks!
